// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {

    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDqtE8doUviburk4LOXcaWSbF-vIj8Cju8',
    appId: '1:542732116696:android:eafb32da17179becd42dad',
    messagingSenderId: '542732116696',
    projectId: 'aaaaaaa-168bf',
    storageBucket: 'aaaaaaa-168bf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyVOq4IxTBCWGHeHqVg43PPOmnLQR2dkw',
    appId: '1:542732116696:ios:1bb47a657cf50be5d42dad',
    messagingSenderId: '542732116696',
    projectId: 'aaaaaaa-168bf',
    storageBucket: 'aaaaaaa-168bf.appspot.com',
    iosClientId: '542732116696-91ncpgl5idlrsrosemmk10atrlpm9vsg.apps.googleusercontent.com',
    iosBundleId: 'com.example.modulProject',
  );
}
